<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="TD-PCs-MacBook-Pro.local" name="English_TCs.ReadingsTCs" tests="83" failures="0" timestamp="30 Sep 2019 15:38:58 GMT" time="4528.252" errors="10">
  <testcase name="Add_Temperature" time="37.251" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.579" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.902" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Above ...&gt; but was:&lt;...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Above ...> but was:<...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Temperature(ReadingsTCs.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Temperature -->
  <testcase name="Add_Temperature" time="17.892" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.884" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.858" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;High&gt; but was:&lt;Above Normal&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<High> but was:<Above Normal>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Temperature(ReadingsTCs.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Temperature -->
  <testcase name="Add_Temperature" time="18.895" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="48.362" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.176" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="47.543" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="19.007" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="17.693" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="18.906" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Temperature" time="17.949" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Above ...&gt; but was:&lt;...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Above ...> but was:<...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Temperature(ReadingsTCs.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Temperature -->
  <testcase name="Add_Temperature" time="18.495" classname="English_TCs.ReadingsTCs"/>
  <testcase name="login" time="58.243" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Steps" time="14.450" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="23.536" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="16.263" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="20.481" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="46.167" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Low&gt; but was:&lt;Steps&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Low> but was:<Steps>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.BloodSugar(ReadingsTCs.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- BloodSugar -->
  <testcase name="BloodSugar" time="16.616" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="18.455" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="17.310" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="18.259" classname="English_TCs.ReadingsTCs"/>
  <testcase name="BloodSugar" time="49.272" classname="English_TCs.ReadingsTCs"/>
  <testcase name="AddWeight" time="48.052" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Weight&gt; but was:&lt;High&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Weight> but was:<High>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.AddWeight(ReadingsTCs.java:170)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- AddWeight -->
  <testcase name="Add_Oxygen_Level" time="17.730" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Oxygen_Level" time="13.236" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Oxygen_Level" time="12.731" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Oxygen_Level" time="41.612" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Low&gt; but was:&lt; &gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Low> but was:< >
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Oxygen_Level(ReadingsTCs.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Oxygen_Level -->
  <testcase name="Add_Oxygen_Level" time="17.620" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Oxygen_Level" time="18.271" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="24.691" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="25.305" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="25.355" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="24.402" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="25.250" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="24.095" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Blood_Pressure" time="24.763" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="41.850" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="17.766" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="18.352" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="46.987" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="19.029" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="19.300" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="18.800" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Heart_Rate" time="18.049" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...&gt; but was:&lt;Below ...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<Below ...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Heart_Rate(ReadingsTCs.java:200)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Heart_Rate -->
  <testcase name="Add_Respiration_Rate" time="645.324" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="48.121" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="17.551" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="18.885" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="18.761" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="18.448" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="19.094" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="46.612" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="44.576" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Respiration_Rate" time="18.140" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_BMI" time="19.772" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Bones_Mass" time="19.722" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Bones_Mass" time="45.187" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...&gt; but was:&lt;Below ...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<Below ...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Bones_Mass(ReadingsTCs.java:230)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Bones_Mass -->
  <testcase name="Add_Bones_Mass" time="20.400" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="21.001" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="21.115" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="20.315" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="19.959" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="21.003" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="20.976" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="21.447" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Muscle_Mass" time="21.425" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Low&gt; but was:&lt;Normal&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Low> but was:<Normal>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_Muscle_Mass(ReadingsTCs.java:238)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_Muscle_Mass -->
  <testcase name="Add_body_Fat" time="19.946" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="19.974" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="34.847" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="21.300" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="20.783" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="20.145" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Fat" time="1888.482" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Water" time="23.134" classname="English_TCs.ReadingsTCs">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Above ...&gt; but was:&lt;...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Above ...> but was:<...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at English_TCs.ReadingsTCs.Add_body_Water(ReadingsTCs.java:254)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Add_body_Water -->
  <testcase name="Add_body_Water" time="22.882" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Water" time="22.240" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Water" time="46.151" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_body_Water" time="22.844" classname="English_TCs.ReadingsTCs"/>
  <testcase name="Add_Fasceral_Fat" classname="English_TCs.ReadingsTCs">
    <skipped/>
  </testcase> <!-- Add_Fasceral_Fat -->
</testsuite> <!-- English_TCs.ReadingsTCs -->
